== PART I. Procedures for Take over
Procedure to use when a GISC starts its GISC watch period:

(a).	Take over the GISC Watch duty according to the agreed roster.

The GISC Watch roster is available here: https://community.wmo.int/en/activity-areas/wis/gisc_watch


(b).	Handover acknowledgement

-  Accept the hand-over-report from previous GISC
-  Send an acknowledgement to confirm receipt. 

Note: To ensure the continuity of GISC Watch, the incoming GISC must begin monitoring duties at the start of its roster period even if the handover email/report has not yet been received.

Sample takeover email:

>  From: GISC Beijing
>  To: GISC Toulouse
>  Cc: gisc-op@groups.wmo.int + wis@wmo.int
>  Subject: GISC WATCH Takeover (16-30 April) confirmed: GISC Watch Report 01-15 April 2025
>  
>  Dear GISC Toulouse,
>  Thank you for your efforts and the handover report. 
>  GISC Beijing will take over the duty from April 16th to 30th 2025.
>  Best regards,
>  GISC Beijing


(c). Review open tickets

At the beginning of its monitoring period, review any open tickets from the previous period.


