name: WIS2 GISC Watch Guide

on:
  push:
    branches:
    - main

env:
  FILE_BASENAME: wis2-gisc-watch-guide

jobs:
  build-wis2-gisc-watch-guide:
    name: Generate documentation
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update -y \
          && sudo apt-get install -y pandoc \
          && sudo gem install asciidoctor asciidoctor-pdf
      - name: checkout repository
        uses: actions/checkout@master
      - name: build documentation
        run: |
          mkdir -p /tmp/wis2-gisc-watch-guide/images \
          && cd gisc-watch-guide \
          && asciidoctor --trace -o /tmp/wis2-gisc-watch-guide/${FILE_BASENAME}.html index.adoc \
          && asciidoctor --trace --backend docbook --out-file - index.adoc | pandoc --from docbook --to docx --output /tmp/wis2-gisc-watch-guide/${FILE_BASENAME}.docx \
          && asciidoctor --trace -r asciidoctor-pdf --trace -b pdf -o /tmp/wis2-gisc-watch-guide/${FILE_BASENAME}.pdf index.adoc \
          && cp images/*.jpeg /tmp/wis2-gisc-watch-guide/images \
          && cd ..
      - name: checkout gh-pages branch
        uses: actions/checkout@master
        with:
          ref: gh-pages
      - name: update gh-pages branch and publish
        run: | 
          git config --global user.email "tomkralidis@gmail.com"
          git config --global user.name "Tom Kralidis"
          rm -rf gisc-watch-guide
          mv -f /tmp/wis2-gisc-watch-guide/* .
          git add .
          git commit -am "update WIS2 GISC Watch Guide build"
          git push
